-- MySQL Script generated by MySQL Workbench
-- Wed Mar 10 15:52:38 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rating_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rating_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rating_system` DEFAULT CHARACTER SET utf8 ;
USE `rating_system` ;

-- -----------------------------------------------------
-- Table `rating_system`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rating_system`.`User` ;

CREATE TABLE IF NOT EXISTS `rating_system`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(30) NULL,
  `last_name` VARCHAR(45) NULL,
  `password` VARCHAR(100) NULL,
  `email` VARCHAR(50) NULL,
  `email_confirmed` TINYINT(1) NULL,
  `created_at` DATETIME NOT NULL,
  `role` ENUM('ADMINISTRATOR', 'SELLER', 'USER') NOT NULL,
  `avg_rating` DOUBLE NULL,
  `approved` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rating_system`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rating_system`.`Comment` ;

CREATE TABLE IF NOT EXISTS `rating_system`.`Comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` TEXT(1000) NOT NULL,
  `author_id` INT NOT NULL,
  `seller_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `approved` TINYINT(1) NOT NULL,
  `rating` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comment_User_idx` (`author_id` ASC) VISIBLE,
  INDEX `fk_Comment_User1_idx` (`seller_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_User`
    FOREIGN KEY (`author_id`)
    REFERENCES `rating_system`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `rating_system`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rating_system`.`Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rating_system`.`Game` ;

CREATE TABLE IF NOT EXISTS `rating_system`.`Game` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `category` ENUM('ACTION', 'ADVENTURE', 'BATTLE_ROYALE', 'BOARD_GAME', 'CARD_GAME', 'CASUAL', 'FIGHTING', 'RACING', 'RPG', 'SHOOTER', 'SIMULATION', 'SPORTS', 'STRATEGY', 'SURVIVAL') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rating_system`.`Game_object`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rating_system`.`Game_object` ;

CREATE TABLE IF NOT EXISTS `rating_system`.`Game_object` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `text` TEXT(1000) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `game_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_GameObject_User1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_GameObject_Game1_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `fk_GameObject_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `rating_system`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GameObject_Game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `rating_system`.`Game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
